export const config = {
  scraper_base_url: 'http://localhost:4004',
  // scraper_base_url: 'http://scraper-service:4004',
  puppeteer_browser_config: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-gpu',
    '--no-first-run',
    '--disable-extensions',
    '--disable-default-apps',
    '--disable-background-networking',
    '--disable-sync',
    '--disable-translate',
    '--hide-scrollbars',
    '--mute-audio',
    '--no-default-browser-check',
    '--ignore-certificate-errors',
    '--ignore-ssl-errors',
    '--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    '--disable-web-security',
    '--disable-features=VizDisplayCompositor',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-renderer-backgrounding',
    '--disable-field-trial-config',
    '--disable-ipc-flooding-protection',
    '--disable-hang-monitor',
    '--disable-prompt-on-repost',
    '--disable-client-side-phishing-detection',
    '--disable-component-extensions-with-background-pages',
    '--safebrowsing-disable-auto-update',
    '--metrics-recording-only',
    '--ignore-certificate-errors-spki-list',
  ],
  timeout: 30000,
  max_products: 5,
};
